sudo: required
language: rust
os:
  - linux
services:
  - docker
rust:
  - stable
cache: cargo
stages:
  - Test
  - name: GitHub Tag Release
    if: tag IS present
  - name: GitHub Master Release
    if: branch = "master" AND type != "pull_request"
jobs:
  include:
    - stage: Test
      script: cargo build --verbose --all && cargo test --verbose --all
    - stage: GitHub Tag Release
      script: "chmod +x ./build-release.sh && ./build-release.sh website ${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
      deploy:
        provider: releases
        api_key:
          secure: rCmxXCLMY4n931cymXX5Z7ZpM1qVIVmMgg7vCy67oG4gOe1mvKAu31x52VXunxc6W0oJbw9oSdzWeq74W2YPKXklcLyYDQZNNbkVqLClNaSStG2zfVd7E9vYfJKfpBN4BzDSfPDr/oENVUPq5C3IaNGWrW/ay6s7H5GOU3oDfdlkOAEHsrgXHZaUyL0hcgOiRzN34cbB909kEcJT4ZcHNYXk3a4MZzmQ3eNp+2Amn9BTQL2QG5bVHFfU0vhRGRpCxD2eaJXBJ4YbOK+UYhtMbfGT+8K+J/DAv2CYq8HwRqI3NEV9THohKwQMSAZSOvxACiJ25Y4dbF8nCzsD0C1ofQ4rjeM3KZqZbJWNeiP+7/bdLUsWjzBnS5DFz8W/AqNIkBTKHzT9YPYeD36PSTxRMFbXyO1ts6L/o85RniwkRpVsVTqAeWhYOVU4VxDimIYV2yny8PUWMtTjaZojKbXA62zGbOpDxlauidEHJXLWzx5o3zrAxvXWdOiZDB9npM/hTv0ASYO6yxY5g4SMHyOFFtbj26I3eWV/DDD8Rz6CJ0UMQnv9NC+hEWNel93gjouFwp59LnUlsMD5VQbQwRzyYjTRAt/UC3rYM3pduJVbyJ6QKE767ylGMahveMj2J9htW3/q4nnZ069TBNfBPoqiBPJlE5kgxr8mpzTZcUHMl0I=
        file_glob: true
        file: website-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*
        skip_cleanup: true
        on:
          repo: friedemannsommer/website
          rust: stable
          tags: true
    - stage: GitHub Master Release
      script: "chmod +x ./build-release.sh && ./build-release.sh website ${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
      deploy:
        provider: releases
        api_key:
          secure: rCmxXCLMY4n931cymXX5Z7ZpM1qVIVmMgg7vCy67oG4gOe1mvKAu31x52VXunxc6W0oJbw9oSdzWeq74W2YPKXklcLyYDQZNNbkVqLClNaSStG2zfVd7E9vYfJKfpBN4BzDSfPDr/oENVUPq5C3IaNGWrW/ay6s7H5GOU3oDfdlkOAEHsrgXHZaUyL0hcgOiRzN34cbB909kEcJT4ZcHNYXk3a4MZzmQ3eNp+2Amn9BTQL2QG5bVHFfU0vhRGRpCxD2eaJXBJ4YbOK+UYhtMbfGT+8K+J/DAv2CYq8HwRqI3NEV9THohKwQMSAZSOvxACiJ25Y4dbF8nCzsD0C1ofQ4rjeM3KZqZbJWNeiP+7/bdLUsWjzBnS5DFz8W/AqNIkBTKHzT9YPYeD36PSTxRMFbXyO1ts6L/o85RniwkRpVsVTqAeWhYOVU4VxDimIYV2yny8PUWMtTjaZojKbXA62zGbOpDxlauidEHJXLWzx5o3zrAxvXWdOiZDB9npM/hTv0ASYO6yxY5g4SMHyOFFtbj26I3eWV/DDD8Rz6CJ0UMQnv9NC+hEWNel93gjouFwp59LnUlsMD5VQbQwRzyYjTRAt/UC3rYM3pduJVbyJ6QKE767ylGMahveMj2J9htW3/q4nnZ069TBNfBPoqiBPJlE5kgxr8mpzTZcUHMl0I=
        file_glob: true
        file: website-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*
        skip_cleanup: true
        draft: true
        on:
          repo: friedemannsommer/website
          rust: stable