sudo: required
language: rust
os:
  - linux
services:
  - docker
rust:
  - stable
stages:
  - Test
  - name: Deploy Lambda
    if: branch = "master" AND type != "pull_request"
jobs:
  include:
    - stage: Test
      script: "cargo check --verbose --all && cargo test --verbose --all"
    - stage: Deploy Lambda
      script: "npm i --silent && ./node_modules/.bin/serverless package"
      deploy:
        provider: script
        script: "./node_modules/.bin/serverless deploy --conceal --stage production"
        skip_cleanup: true
        on:
          branch: master