version: 0.2
            
phases:
  install:
    commands:
      - "curl -sSf https://build.travis-ci.com/files/rustup-init.sh | sh -s -- --default-toolchain=stable -y"
      - "PATH=$PATH:$HOME/.cargo/bin"
  build:
    commands:
      - "cargo check --verbose --all"
      - "cargo test --verbose --all"
      - "cargo build --verbose --release"
artifacts:
  files:
    - target/release/website
  name: website
  discard-paths: yes
cache:
  paths:
    - node_modules
    - target