[package]
name = "website"
edition = "2018"
version = "1.0.1"
authors = ["Friedemann Sommer <contact@friedemannsommer.com>"]

[[bin]]
name = "website"
path = "src/main.rs"

[dependencies]
lambda_runtime = "0.2"
lambda_http = "0.1"
handlebars = "1.1"
lazy_static = "1.3"
serde_json = "1.0"
html-minifier = "1.1.4"
