[package]
name = "website"
version = "0.1.9"
authors = ["Friedemann Sommer <contact@friedemannsommer.com>"]

[[bin]]
name = "website"
path = "src/main.rs"

[dependencies]
actix = "0.7"
actix-web = { version = "0.7" }
tera = "0.11"
lazy_static = "1.2.0"
