[package]
name = "website"
version = "0.1.9"
authors = ["Friedemann Sommer <contact@friedemannsommer.com>"]

[[bin]]
name = "website"
path = "src/main.rs"

[dependencies]
actix = "0.7"
actix-web = "0.7"
handlebars = "1.1.0"
lazy_static = "1.2.0"
serde_json = "1.0.39"
html-minifier = "1.1.4"
