[package]
name = "website"
version = "0.1.0"
authors = ["Friedemann Sommer <friedemannsommer@yahoo.de>"]

[dependencies]
openssl = { version="0.10" }
actix = "0.7"
actix-web = { version = "0.7", features=["ssl"] }