[package]
name = "website"
version = "0.1.0"
authors = ["Friedemann Sommer <friedemannsommer@yahoo.de>"]

[[bin]]
name = "website"
path = "src/main.rs"

[dependencies]
actix = "0.7"
actix-web = { version = "0.7" }
