[package]
name = "website"
edition = "2018"
version = "1.0.9"
authors = ["Friedemann Sommer <contact@friedemannsommer.com>"]

[[bin]]
name = "website"
path = "src/main.rs"

[dependencies]
lambda_runtime = "0.2"
lambda_http = "0.1"
handlebars = "2.0"
lazy_static = "1.4"
serde_json = "1.0"
html-minifier = "1.1"
rust-crypto = "0.2"
data-encoding = "2.1"
