[package]
name = "website"
edition = "2018"
version = "1.0.13"
authors = ["Friedemann Sommer <contact@friedemannsommer.com>"]

[[bin]]
name = "website"
path = "src/main.rs"

[dependencies]
lambda_runtime = "0.2.1"
lambda_http = "0.1.1"
handlebars = "2.0.2"
lazy_static = "1.4.0"
serde_json = "1.0.44"
html-minifier = "1.1.14"
rust-crypto = "0.2.36"
data-encoding = "2.1.2"
