title = "Friedemann Sommer"
description = "A Software Engineer at advanced STORE"
base_url = "https://www.friedemannsommer.com"

default_language = "en"

generate_feeds = true
feed_filenames = [
    "atom.xml",
    "rss.xml",
]

compile_sass = true
build_search_index = false
minify_html = true
hard_link_static = false

taxonomies = [
    { name = "tags", feed = false },
]

[markdown]
bottom_footnotes = true
external_links_no_follow = true
external_links_no_referrer = true
external_links_target_blank = true
highlight_code = true
highlight_theme = "visual-studio-dark"
lazy_async_image = true
render_emoji = true
smart_punctuation = false

[link_checker]
skip_prefixes = [
    "https://advanced-store.com/",
    "https://github.com/",
    "https://twitter.com/",
    "https://www.linkedin.com/",
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
include_title = true
include_description = true
include_path = false
include_content = true

[extra]
title_separator = "-"
main_menu = [
    { url = "/", name = "Home" },
    { url = "/blog/", name = "Blog" },
    { url = "/projects/", name = "Projects" },
    { url = "/contact/", name = "Contact" },
]
