title = "Friedemann Sommer"
description = "A Software Engineer at advanced STORE"
base_url = "https://www.friedemannsommer.com"

default_language = "en"
feed_filename = "atom.xml"

compile_sass = true
build_search_index = false
minify_html = true
generate_feed = true
hard_link_static = false

taxonomies = [
    { name = "tags", feed = true },
]

[markdown]
highlight_theme = "material-dark"
highlight_code = true
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[link_checker]
skip_prefixes = [
    "https://advanced-store.com/",
    "https://github.com/",
    "https://www.linkedin.com/"
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
include_title = true
include_description = true
include_path = false
include_content = true

[extra]
main_menu = [
    { url = "$BASE_URL/", name = "Home" },
    { url = "$BASE_URL/blog/", name = "Blog" },
    { url = "$BASE_URL/contact/", name = "Contact" },
]
