title = "Friedemann Sommer"
description = "Friedemann Sommer Software Engineer at advanced STORE"
base_url = "https://friedemannsommer.github.io/website"

default_language = "en"
feed_filename = "atom.xml"

compile_sass = true
build_search_index = true
minify_html = true
generate_feed = true
hard_link_static = false

taxonomies = [
    { name = "tags", feed = true },
]

[markdown]
highlight_theme = "two-dark"

highlight_code = true
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[link_checker]
skip_prefixes = [
    "https://advanced-store.com/",
    "https://github.com/",
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
include_title = true
include_description = true
include_path = false
include_content = true

[extra]
main_menu = [
    { url = "$BASE_URL/", name = "Home" },
    { url = "$BASE_URL/about/", name = "About" },
]
