service: website
provider:
  name: aws
  runtime: rust
  memorySize: 128
  region: eu-central-1
  logRetentionInDays: 7
  deploymentBucket:
    maxPreviousDeploymentArtifacts: 1
  endpointType: regional
  apiGateway:
    minimumCompressionSize: 1024
    metrics: false
  timeout: 15
  tracing:
    apiGateway: false
    lambda: false
  logs:
    restApi:
      accessLogging: true
      executionLogging: false
      fullExecutionData: false
    httpApi:
      format: false

package:
  individually: true

plugins:
  - serverless-rust

custom:
  rust:
    dockerless: true

functions:
  render:
    handler: website
    memorySize: 128
    timeout: 15
    logRetentionInDays: 7
    events:
      - http:
          path: '/'
          method: GET
      - http:
          path: '/{path+}'
          method: GET
