name: public - CI

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'
      - 'sass/**'
      - 'static/**'
      - 'templates/**'
      - 'config.toml'
      - '.github/workflows/publish.yml'

env:
  ZOLA_VERSION: v0.17.2

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Download zola
        run: curl -sL https://github.com/getzola/zola/releases/download/${{ env.ZOLA_VERSION }}/zola-${{ env.ZOLA_VERSION }}-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
      - name: Build site
        run: zola build -o public
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: public
