name: test - CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

env:
  ZOLA_VERSION: v0.21.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Download zola
        run: curl -sL https://github.com/getzola/zola/releases/download/${{ env.ZOLA_VERSION }}/zola-${{ env.ZOLA_VERSION }}-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
      - name: Check site
        run: zola check
